### ISSUE TITLE
Some questions and improvement suggestions

### ISSUE THREAD

**Issue by DmitrySharabin** [nudeui/element#1]
Before sending these changes as a PR, I would appreciate it if we could discuss them first.

I would suggest defining props _before_ defining events (by moving this code higher):

https://github.com/nudeui/element/blob/eac7d8bb3281a96d7422279fea755c97be35b3c3/src/Element.js#L44-L46

Now, when we define events first, we lose the corresponding class props (before they have even had a chance to be defined) because of this line (this line is executed when we define events as props):

https://github.com/nudeui/element/blob/eac7d8bb3281a96d7422279fea755c97be35b3c3/src/props/defineProps.js#L25

<hr>

When adding a prop, we update its dependents. However, at that moment, not all dependents might be instances of the `Prop` class. This means, this line would throw:

https://github.com/nudeui/element/blob/eac7d8bb3281a96d7422279fea755c97be35b3c3/src/props/Props.js#L104

So, I would suggest slightly changing this line, e.g., like so:

```js
let dependencies = [...(prop.dependencies ?? [])]
```

<hr>

In this line

https://github.com/nudeui/element/blob/eac7d8bb3281a96d7422279fea755c97be35b3c3/src/props/defineProps.js#L35

The `element` parameter comes from nowhere (and is `undefined`). Should it be equal to `this` here?

<hr>

I also noticed that we don't call `attributeChangedCallback()` anywhere, even though we re-defined it. Shouldn't we call it here:

https://github.com/nudeui/element/blob/eac7d8bb3281a96d7422279fea755c97be35b3c3/src/props/Props.js#L66

instead of `this.attributeChanged(element, name)` should be `element.attributeChangedCallback(name)`?

<hr>

When adding a prop, we should return it. Otherwise, props whose default values are functions will be `undefined`.

We should fix this code:

https://github.com/nudeui/element/blob/eac7d8bb3281a96d7422279fea755c97be35b3c3/src/props/Props.js#L38-L42

```diff
+		let prop;
		for (let [name, spec] of Object.entries(props)) {
-			let prop = new Prop(name, spec, this);
+			prop = new Prop(name, spec, this);
			this.set(name, prop);
			Object.defineProperty(this.Class.prototype, name, prop.getDescriptor());
		}

		this.updateDependents();
+		return prop;
```

For example, see this fragment:

https://github.com/nudeui/element/blob/eac7d8bb3281a96d7422279fea755c97be35b3c3/src/props/Prop.js#L28-L31

**Comment by LeaVerou** [comment]
Thanks for debugging!

> Now, when we define events first, we lose the corresponding class props (before they have even had a chance to be defined) because of this line (this line is executed when we define events as props)

You're absolutely right! 

----

> So, I would suggest slightly changing this line, e.g., like so:

The right course of action is not to drop the dependencies but to ensure all props are created when this runs. Why are they not? What changed?

---

> The element parameter comes from nowhere (and is undefined). Should it be equal to this here?

Yes!

---

> When adding a prop, we should return it. Otherwise, props whose default values are functions will be undefined.

But there's nothing reasonable to return when adding multiple props. I see two solutions:

1. We change the code in Prop.js to look up the prop after by name. 
2. We split `add()` into `add()` for 1 prop, which returns it and `addAll()` that adds multiple props.

I think I'm leaning towards 1, as with 2 would be hard to know when to call `updateDependents()`.
