### ISSUE TITLE
`PROPNAMEchange` events don't have a `detail` property

### ISSUE THREAD

**Issue by DmitrySharabin** [nudeui/element#13]
On a prop change, we dispatch a `propchange` event—an instance of `PropChangeEvent`.

https://github.com/nudeui/element/blob/713e5a0fa8400c337824ac339b6f76a94a2d8624/src/props/Prop.js#L228-L238

However, when we dispatch the corresponding `PROPNAMEchange` event
https://github.com/nudeui/element/blob/713e5a0fa8400c337824ac339b6f76a94a2d8624/src/events/defineEvents.js#L118-L122
we lose the `detail` property. The `options` object of the `PropChangeEvent` constructor
https://github.com/nudeui/element/blob/713e5a0fa8400c337824ac339b6f76a94a2d8624/src/props/PropChangeEvent.js#L4 has the `isTrusted` property only. None of the other properties.

**Comment by DmitrySharabin** [comment]
Testcase is a `gamutchange` event on the `<color-swatch>` component.

**Comment by LeaVerou** [comment]
Oh interesting, I had assume `event` would pass these along. This should be an easy bug to fix.
