### ISSUE TITLE
`parse()` is not called on a pre-existing value for the prop

### ISSUE THREAD

**Issue by DmitrySharabin** [nudeui/element#14]
Testcase

https://codepen.io/leaverou/pen/rNgLOEM

**Comment by DmitrySharabin** [comment]
I also noticed that if the `value2` prop has a default value, it's not considered—`foobar.value2` still returns `"1"`.

**Comment by LeaVerou** [comment]
> I also noticed that if the `value2` prop has a default value, it's not considered—`foobar.value2` still returns `"1"`.

That is the expected behavior (modulo the lack of parsing) since the property is not empty

**Comment by LeaVerou** [comment]
Ok after taking a look at the code, I think I understand what is happening. The property accessors are defined on the prototype of the element class (`Props.js` L42). Therefore, having a property set directly on the element, before any setter is defined, effectively overrides the accessors entirely.

Take a look at this testcase which doesn't depend on elements at all: 
<img width="597" alt="image" src="https://github.com/nudeui/element/assets/175836/b030b685-94ff-4bd9-aa41-a7e0ba01d08b">
