### ISSUE TITLE
Allow recursive type options

### ISSUE THREAD

**Issue by LeaVerou** [nudeui/element#21]
This came up in https://github.com/color-js/elements/pull/80

We can currently specify that a prop should be parsed as an array of objects, by specifying `{type: Array, typeOptions: {itemType: Object}}` however we cannot specify any type options for these objects (`defaultKey`, `defaultValue`, `valueType`, etc.).

Type definitions should be recursive, which means the current design is not ideal.

**Comment by LeaVerou** [comment]
Proposed solution: Instead of two separate properties, `type` and `typeOptions`, types can be either:
- A function (`Object`)
- An object with metadata, one of which is the constructor. Property name TBB, but how about `is`?

So the gamuts example could be something like:

```js
prop: {
	type: {
		is: Array,
		itemType: {
			is: Map,
			keyType: ColorSpace,
			defaultValue: v => v.name,
		}
	}
}
```

**Comment by DmitrySharabin** [comment]
Do we plan to support a shortcut to specify types?

For example, for `value` prop, it would be nice if we could write

```js
value: {
	type: String
}
```

instead of

```js
value: {
	type: {
		is: String
	}
}
```

**Comment by DmitrySharabin** [comment]
> Property name TBB, but how about is?

I like `is`—the code is read as plain English. So, seconded for `is`.

**Comment by LeaVerou** [comment]
> Do we plan to support a shortcut to specify types?
> 
> For example, for `value` prop, it would be nice if we could write
> 
> ```js
> value: {
> 	type: String
> }
> ```
> 
> instead of
> 
> ```js
> value: {
> 	type: {
> 		is: String
> 	}
> }
> ```

Yes, that’s the whole point, see the two bullet points in my proposal. What you're saying is bullet point 1.

**Comment by LeaVerou** [comment]
But you just made me realize something: it may be confusing to have two properties for this, `type` and `is`. I wonder if it should just be `type`, but then it reads kind of repetitive:

```js
gamuts: {
	type: {
		type: Array,
		itemType: {
			type: Map,
			keyType: ColorSpace,
			defaultValue: v => v.name,
		}
	}
}
```

**Comment by DmitrySharabin** [comment]
> Yes, that’s the whole point, see the two bullet points in my proposal. What you're saying is bullet point 1.

I got it. Thanks. That's rad!

I still like `is` in nested objects—it reads effortlessly. 😛

**Comment by DmitrySharabin** [comment]
Among these, I most like option 5. Vote for this. :)

**Comment by LeaVerou** [comment]
Another option: `has` that takes either a single `Function` value or an array of two `Function` values. If one `Function` value is provided for a type that can also have a key type (currently only `Map`) it is converted to `has: [, Type]`.

```js
colors: { type: Object, has: Color },
colors: { type: Array, has: Color },
```

Pros: 
- Allows extending to more complex data types as well
- Goes nicely together with `is`

Cons:
- A little awkward when specifying a key type only (`has: [KeyType]`). Though that’s pretty rare.
- Does it make sense what this is by its name?

**Comment by DmitrySharabin** [comment]
I like the shorter name. However, If I see this code for the first time, honestly, I wouldn't guess that `has` is the type of element (for lists) or values type (for objects). For me, it's like a list has an element of type `Color` (not all its elements have this type) or an object with a `Color` property. 🤷‍♂️

At the time of writing this comment, I thought of another option: `of`:

```js
colors: { type: Object, of: Color },
colors: { type: Array, of: Color },
```

**Comment by LeaVerou** [comment]
Yeah, I was worried about that. `of` makes sense for lists, but not really for dictionaries.
