### ISSUE TITLE
Should the names of `PropChangeEvent` and `firePropChangedEvent` match each other?

### ISSUE THREAD

**Issue by DmitrySharabin** [nudeui/element#25]
We have `PropChangeEvent`,

https://github.com/nudeui/element/blob/42187111119b2ccbd195e1649c7e3cda90a78d98/src/props/PropChangeEvent.js#L3

but the method which fires it is called `firePropChangedEvent` (_change**D**_)

https://github.com/nudeui/element/blob/42187111119b2ccbd195e1649c7e3cda90a78d98/src/props/Props.js#L134

Is it by design?

**Comment by LeaVerou** [comment]
Yes, they should be. Nice catch!
