### ISSUE TITLE
Can't specify `Object` as type because the built-in `Object` class already has its own properties (methods) `keys` and `values`

### ISSUE THREAD

**Issue by DmitrySharabin** [nudeui/element#27]
I stumbled on this issue when I tried to define the `coords` property like so:

```js
coords: {
	type: {
		is: Array,
		values: Object,
	},
```

When we parse a value and pass it along with its type to the `parseEntries()` method https://github.com/nudeui/element/blob/eebac9359bf0eb32da7e3fb406716f35a7247677/src/props/types/dictionaries.js#L4
we destructure the `keys` property (a function), even though we didn't specify it in our type when defining the prop. It was destructured from the built-in `Object` class.

On the next step, `keys` is defined, and the following block of code is executed

https://github.com/nudeui/element/blob/eebac9359bf0eb32da7e3fb406716f35a7247677/src/props/types/dictionaries.js#L43-L45

the generic `parse()` function is called with `keys()` as a type. And of course this function throws on this line

https://github.com/nudeui/element/blob/eebac9359bf0eb32da7e3fb406716f35a7247677/src/props/types/basic.js#L25

I can also suggest that we'll face the same issue with `Map`s.

We have a workaround, but I think everything should work without it:

```js
coords: {
	type: {
		is: Array,
		values: { is: Object },
	},
```

**Comment by LeaVerou** [comment]
Nice catch! Yes, this should definitely be fixed in Nude Element. When do we pass the raw type to `parseEntries()` without calling `resolve()` on it first?

**Comment by DmitrySharabin** [comment]
> When do we pass the raw type to `parseEntries()` without calling `resolve()` on it first?

It happens in this line

https://github.com/nudeui/element/blob/6871a0495f6c139574bd28a09184f4732d37fc12/src/props/types/dictionaries.js#L93

Here is the trace. After `NudeElement` splits a string into an array of strings, it tries to parse every chunk as an object.

<img width="995" alt="image" src="https://github.com/nudeui/element/assets/9166277/b9ae41f5-e1fd-4215-b130-4b922e523aa9">


Then, `NudeElement` correctly determines that it needs to use `parse()` from `dictionaries.js`.

<img width="1085" alt="image" src="https://github.com/nudeui/element/assets/9166277/d2e7ff71-d206-4ef6-89bf-2b90111db764">

And calls `parseEntries()` passing the raw `Object` type as `options`.

<img width="1084" alt="image" src="https://github.com/nudeui/element/assets/9166277/1ae105be-f3f5-45f1-aebc-94bb6dae7ea3">

And destructures `keys()` and `values()` from the passed raw `Object`.

<img width="1081" alt="image" src="https://github.com/nudeui/element/assets/9166277/81672ecc-0a31-475d-a579-737b24670325">

**Comment by LeaVerou** [comment]
But `options` should never be `Object`, at that point it should be a plain object with `is`.
Ah, I see. We should replace `type` with `resolve(type)` and destructure that.
