### ISSUE TITLE
Can `defineEvents()` be used without props?

### ISSUE THREAD

**Issue by LeaVerou** [nudeui/element#4]
If a component is managing its own props, can it still use `defineEvents()` to add events that create on* attributes? Needs testing.

**Comment by DmitrySharabin** [comment]
If I understand correctly, [the things we did with `<color-swatch>`](https://github.com/color-js/elements/pull/37) are illustrations that `defineEvents()` can be used without props.

However, the component should:

- Have an `initQueue` static array (all needed initialization steps will be added inside it)
- Execute all the steps from the queue after the component is connected, like so (inside `connectedCallback()`):

```js
this.constructor.initQueue.forEach(init => init.call(this));
```

**Comment by LeaVerou** [comment]
Or it needs to assign the return value to a variable (e.g. `initEvents`) and then make sure to call it.
